'use strict';

window.questions = [
  { "question": "AA", "answer": "Area Administrator" },
  { "question": "AAG", "answer": "Assistant Attorney General" },
  { "question": "ACE", "answer": "Adverse Childhood Experience" },
  { "question": "ACES", "answer": "Automated Client Eligibility System" },
  { "question": "AG", "answer": "State Attorney General" },
  { "question": "APS", "answer": "Adult Protective Services" },
  { "question": "ARY", "answer": "At-Risk Youth" },
  { "question": "ASL", "answer": "American Sign Language" },
  { "question": "BCCU", "answer": "Background Check Clearance Unit" },
  { "question": "BIA", "answer": "Bureau of Indian Affairs" },
  { "question": "BRS/GC", "answer": "Behavior Rehabilitation Services/Group Care" },
  { "question": "CA", "answer": "Children’s Administration" },
  { "question": "CA/N", "answer": "Child Abuse and Neglect" },
  { "question": "CASA", "answer": "Court Appointed Special Advocate" },
  { "question": "CFE", "answer": "Comprehensive Family Evaluation" },
  { "question": "CFSR", "answer": "Child and Family Safety Review" },
  { "question": "CFWS", "answer": "Child and Family Welfare Services" },
  { "question": "CHET", "answer": "Child Health and Education Tracking" },
  { "question": "CHINS", "answer": "Child in Need of Services" },
  { "question": "CPA", "answer": "Child Placing Agency" },
  { "question": "CPS", "answer": "Child Protective Services" },
  { "question": "CPT", "answer": "Child Protection Team" },
  { "question": "CQI", "answer": "Continuous Quality Improvement" },
  { "question": "CRC", "answer": "Crisis Residential Center" },
  { "question": "CSEC", "answer": "Commercially Sexually Exploited Children" },
  { "question": "CSO", "answer": "Community Services Office" },
  { "question": "CWTAP", "answer": "Child Welfare Training and Advancement Program" },
  { "question": "DBHR", "answer": "Division of Behavioral Health and Recovery" },
  { "question": "DCFS", "answer": "Division of Children and Family Services" },
  { "question": "DCS", "answer": "DSHS Division of Child Support" },
  { "question": "DD", "answer": "Developmentally Disabled" },
  { "question": "DDD", "answer": "Division of Developmental Disabilities" },
  { "question": "DEL", "answer": "Department of Early Learning" },
  { "question": "DLR", "answer": "Division of Licensed Resources" },
  { "question": "DOC", "answer": "Department of Corrections" },
  { "question": "DOH", "answer": "Department of Health" },
  { "question": "DSHS", "answer": "Department of Social and Health Services" },
  { "question": "DVR", "answer": "DSHS Division of Vocational Rehabilitation" },
  { "question": "EAP", "answer": "Employee Assistance Program" },
  { "question": "ECP", "answer": "Exceptional Cost Plan" },
  { "question": "EFC", "answer": "Extended Foster Care" },
  { "question": "EFSS", "answer": "Early Family Support Services" },
  { "question": "EPSDT", "answer": "Early and Periodic Screening, Diagnosis, & Treatment" },
  { "question": "ESA", "answer": "DSHS Economic Services Administration" },
  { "question": "ETV", "answer": "Educational Training Voucher" },
  { "question": "FAR", "answer": "Family Assessment Response" },
  { "question": "FARFA", "answer": "Family Assessment Response Family Assessment" },
  { "question": "FCAP", "answer": "Foster Care Assessment Program" },
  { "question": "FFT", "answer": "Functional Family Therapy" },
  { "question": "FGC", "answer": "Family Group Conference" },
  { "question": "FOSA", "answer": "Family and Offender Supervision Alternative Program" },
  { "question": "FPAWS", "answer": "Foster Parents Association of Washington State" },
  { "question": "FPS", "answer": "Family Preservation Services" },
  { "question": "FRS", "answer": "Family Reconciliation Services" },
  { "question": "FTDM", "answer": "Family Team Decision Making Meeting" },
  { "question": "FTE", "answer": "Full Time Employee/Equivalent" },
  { "question": "FVS", "answer": "Family Voluntary Services" },
  { "question": "FWB", "answer": "CCU Fostering Well Being - Care Coordination Unit" },
  { "question": "GAL", "answer": "Guardian Ad Litem" },
  { "question": "HBS", "answer": "Home Based Services" },
  { "question": "HSS", "answer": "Home Support Specialist" },
  { "question": "IA", "answer": "Investigative Assessment" },
  { "question": "ICAMA", "answer": "Interstate Compact on Adoption and Medical Assistance" },
  { "question": "ICPC", "answer": "Interstate Compact on the Placement of Children" },
  { "question": "ICW", "answer": "Indian Child Welfare" },
  { "question": "ICWA", "answer": "Indian Child Welfare Act of 1978" },
  { "question": "IEP", "answer": "Individualized Education Plan" },
  { "question": "IEPA", "answer": "Inter-Ethnic Placement Act" },
  { "question": "IFF", "answer": "Initial Face to Face Visit (CPS response to an intake)" },
  { "question": "IFPS", "answer": "Intensive Family Preservation Services (HomeBuilders)" },
  { "question": "ILP", "answer": "Independent Living Program" },
  { "question": "ILS", "answer": "Independent Living Skills" },
  { "question": "ISSD", "answer": "Information Systems Services Division" },
  { "question": "ITA", "answer": "Involuntary Treatment Act" },
  { "question": "JRA", "answer": "Juvenile Rehabilitation Administration" },
  { "question": "LE", "answer": "Law Enforcement" },
  { "question": "LEP", "answer": "Limited English Proficiency" },
  { "question": "LIST", "answer": "DSHS Office of Language Interpreter Services and Translations" },
  { "question": "LMS", "answer": "Learning Management System" },
  { "question": "MEPA", "answer": "Multi-Ethnic Placement Act (42 USC 5115a)" },
  { "question": "MLR", "answer": "Minimum Licensing Requirements" },
  { "question": "MOU", "answer": "Memorandum of Understanding" },
  { "question": "MPC", "answer": "Medicaid Personal Care" },
  { "question": "MS", "answer": "Mail Stop" },
  { "question": "NCIC", "answer": "National Crime Information Center" },
  { "question": "NEO", "answer": "New Employee Orientation" },
  { "question": "NWAE", "answer": "Northwest Adoption Exchange" },
  { "question": "OFCL", "answer": "Office of Foster Care Licensing" },
  { "question": "OPD", "answer": "Office of Public Defense" },
  { "question": "OPD", "answer": "Original Placement Date" },
  { "question": "PAAY", "answer": "Physically Aggressive/Assaultive Youth" },
  { "question": "PBC", "answer": "Performance Based Contracting" },
  { "question": "PCIT", "answer": "Parent-Child Interaction Therapy" },
  { "question": "PDP", "answer": "Performance Development Plan" },
  { "question": "PIP", "answer": "Performance Improvement Plan" },
  { "question": "QA", "answer": "CA Office of Quality Assurance and Training" },
  { "question": "RA", "answer": "Regional Administrator" },
  { "question": "RCW", "answer": "Revised Code of Washington" },
  { "question": "RMTS", "answer": "Random Moment Time Study" },
  { "question": "RSN", "answer": "Regional Support Network" },
  { "question": "RSO", "answer": "Registered Sex Offender" },
  { "question": "RTS/BRS", "answer": "Rehabilitative Treatment Services/ Behavior Rehabilitation Services" },
  { "question": "SACWIS", "answer": "Statewide Automated Child Welfare Information System" },
  { "question": "SAY", "answer": "Sexually Aggressive Youth" },
  { "question": "SSI", "answer": "Supplemental Security Income" },
  { "question": "SSODA", "answer": "Special Sex Offender Disposition Alternative Program" },
  { "question": "SSPS", "answer": "Social Service Payment System" },
  { "question": "STD/ STI", "answer": "Sexually Transmitted Disease/ Sexually Transmitted Infection" },
  { "question": "TANF", "answer": "Temporary Assistance for Needy Families" },
  { "question": "TCC", "answer": "Therapeutic Child Care" },
  { "question": "TEMS", "answer": "Travel and Expense Management System" },
  { "question": "TTY", "answer": "Teletypewriter" },
  { "question": "VGAL", "answer": "Volunteer Guardian Ad Litem" },
  { "question": "VPA", "answer": "Voluntary Placement Agreement" },
  { "question": "VSA", "answer": "Voluntary Service Agreement" },
  { "question": "WAC", "answer": "Washington Administrative Code" },
  { "question": "WARE", "answer": "Washington Adoption Resource Exchange" },
  { "question": "WIC", "answer": "Women, Infants, and Children Program" },
  { "question": "WSP", "answer": "Washington State Patrol" }
];
